doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '9.6'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        mappings:
            UserModel:
                type: yml
                dir: '%kernel.project_dir%/src/Entity/config/doctrine'
                prefix: 'App\Entity'
