version: '3.7'
services:
  postgres:
    build: docker/postgres
    container_name: ${APP_NAME}.postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432

  webserver:
    build:
      context: docker/nginx
    container_name: ${APP_NAME}.webserver
    volumes:
      - ./public:/var/www/project/public
      - ./vendor:/var/www/project/vendor:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    container_name: ${APP_NAME}.php-fpm
    working_dir: /var/www/project
    volumes:
      - ~/.composer:/.composer
      - ./:/var/www/project:delegated
      - ./vendor:/var/www/project/vendor:cached
      - /var/www/project/var/cache
    links:
      - postgres

networks:
  default:
    external:
      name: helpcrunch